// swift-tools-version:5.9
// Generated by `:library:generatePackageSwift` — do not edit manually.
import PackageDescription

let package = Package(
    name: "pg",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(
            name: "pg",
            targets: ["edfapay_pg_sdk"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "edfapay_pg_sdk",
            path: "edfapay_pg_sdk.xcframework"
        ),
    ]
)
