// swift-tools-version:5.9
// Generated by `:library:writePackageSwiftVariants` — do not edit manually.
import PackageDescription

let package = Package(
    name: "edfapay_pg_sdk",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "edfapay_pg_sdk", targets: ["edfapay_pg_sdk"])
    ],
    targets: [
        .binaryTarget(
            name: "edfapay_pg_sdk",
            path: "edfapay_pg_sdk.release.xcframework.zip"
        )
    ]
)
